name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
      - redis_password
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NETDATA_USER=${NETDATA_USER}
    secrets:
      - netdata_password
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  ftp:
    build:
      context: ./bonus/ftp
    container_name: ftp
    environment:
      - FTP_USER=${FTP_USER}
    secrets:
      - ftp_user_password
    ports:
      - "20:20"
      - "21:21"
      - "50000-50010:50000-50010"
    volumes:
      - wordpress-data:/mnt/ftpdata
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  redis:
    build:
      context: ./bonus/redis
    container_name: redis
    secrets:
      - redis_password
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - inception
    restart: always

  adminer:
    build:
      context: ./bonus/adminer
    container_name: adminer
    networks:
      - inception
    restart: always

  netdata:
    build:
      context: ./bonus/netdata
    container_name: netdata
    pid: host
    user: root
    networks:
      - inception
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - NETDATA_DISABLE_CLOUD=1
      - DO_NOT_TRACK=1
      - NETDATA_ANONYMOUS_STATISTICS=0
    volumes:
      - netdatacache:/opt/netdata/var/cache/netdata
      - netdataconfig:/opt/netdata/etc/netdata
      - netdatalib:/opt/netdata/var/lib/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/redis
  netdatacache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/netdata/cache
  netdataconfig:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/netdata/config
  netdatalib:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/netdata/lib

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  netdata_password:
    file: ../secrets/netdata_password.txt
