name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  ftp:
    build:
      context: ./requirements/ftp
    container_name: ftp
    environment:
      - FTP_USER=${FTP_USER}
    secrets:
      - ftp_user_password
    ports:
      - "20:20"
      - "21:21"
      - "50000-50010:50000-50010"
    volumes:
      - wordpress-data:/mnt/ftpdata
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt
