FROM alpine:3.22.2

RUN addgroup -g 1000 -S wp-data && \
    adduser -u 1000 -S -D -H -G wp-data wp-data

RUN apk update && \
    apk add --no-cache \
    php84 \
    php84-curl \
    php84-dom \
    php84-exif \
    php84-fileinfo \
    php84-fpm \
    php84-gd \
    php84-json \
    php84-mysqli \
    php84-mbstring \
    php84-opcache \
    php84-openssl \
    php84-phar \
    php84-xml \
    php84-zip \
    wget && \
    ln -s /usr/bin/php84 /usr/bin/php && \
    mkdir -p /var/www/html && \
    wget https://wordpress.org/wordpress-6.8.3.tar.gz && \
    tar -xvzf wordpress-6.8.3.tar.gz -C /var/www/html --strip-components=1 && \
    rm wordpress-6.8.3.tar.gz && \
    chown -R wp-data:wp-data /var/www/html && \
    wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

COPY ./files/www.conf /etc/php84/php-fpm.d/www.conf
COPY ./files/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /var/www/html

EXPOSE 9000

LABEL description="wordpress"

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
