FROM alpine:3.22.2

RUN apk update && apk add --no-cache busybox-extras && \
    mkdir -p /var/www/html

COPY ./files/* /var/www/html

LABEL description="docs"

EXPOSE 8080

CMD ["busybox-extras", "httpd", "-f", "-p", "8080", "-h", "/var/www/html"]
